package problem2;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Solution to problem 2
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 			1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class EvenFibonacciSum {

	public static void main(final String[] args) {
		final long startTime = System.currentTimeMillis();

		System.out.println("The answer is: " + calculateSolution());

		final long endTime = System.currentTimeMillis();
		System.out.println("The solution took: " + (endTime - startTime) + " milliseconds");
	}

	private static BigDecimal calculateSolution() {

		final List<BigDecimal> fibonacci = EvenFibonacciSum.getFibonacciSequence();

		BigDecimal total = BigDecimal.ZERO;

		for (final BigDecimal bigDecimal : fibonacci) {
			if( bigDecimal.intValue() % 2 == 0 ) {
				total = total.add(bigDecimal);
			}
		}

		return total;
	}

	private static List<BigDecimal> getFibonacciSequence() {
		final List<BigDecimal> fibonacci = new ArrayList<BigDecimal>();

		BigDecimal i = BigDecimal.valueOf(1);
		BigDecimal j = BigDecimal.valueOf(2);
		BigDecimal k = BigDecimal.ZERO;

		fibonacci.add(i);
		fibonacci.add(j);

		do {
			k = i.add(j);
			fibonacci.add(k);

			i = j;
			j = k;
		}
		while( k.compareTo(BigDecimal.valueOf(4000000)) == -1 );

		return fibonacci;
	}
}