package problem12;

/**
 * Solution to Problem 12
 * 
 * 
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 * 
 * What is the value of the first triangle number to have over five hundred divisors?
 */
public class TriangularNumber500Factors {

    public static void main(final String[] args) {
	long triangleNumber = 0L;

	for( long i = 1; i>0; i++ ) {
	    triangleNumber = triangleNumber + i;

	    int numberOfDivisors = 2;

	    final double triangleNumberRoot = Math.sqrt(triangleNumber);
	    if(triangleNumberRoot % 1 == 0) {
		numberOfDivisors++;
	    }

	    for( int j = 2; j < triangleNumberRoot; j++ ) {
		if(triangleNumber % j == 0) {
		    numberOfDivisors += 2;
		}
	    }

	    if(numberOfDivisors > 500) {
		System.out.println(triangleNumber);
		break;
	    }
	}
    }
}